on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: setup deps
      run: sudo apt install axel binfmt-support qemu-user-static -y
    - name: clone fs-arm64
      run: axel https://cdimage.ubuntu.com/ubuntu-base/focal/daily/current/focal-base-arm64.tar.gz
    - name: extract fs-arm64
      run: mkdir -pv fs-arm64-arm64-arm64-arm64; sudo tar -xvpzf focal-base-arm64.tar.gz -C fs-arm64
    - name: Setup qemu
      run: sudo cp /bin/qemu-arm-static fs-arm64/bin ;sudo service binfmt-support start
    - name: mount fs-arm64
      run: sudo mount --rbind /dev fs-arm64/dev; sudo mount -t proc proc fs-arm64/proc;sudo mount -t sysfs-arm64 /sys fs-arm64/sys
    - name: setup network
      run: sudo touch fs-arm64/etc/resolv.conf;echo nameserver 8.8.8.8 | sudo tee fs-arm64/etc/resolv.conf
    - name: fix up fs-arm64
      run: sudo cp -v payload/stage1.sh fs-arm64/stage1.sh; sudo cp -v payload/stage2.sh fs-arm64/stage2.sh; sudo chroot fs-arm64 bash /stage1.sh; sudo chroot fs-arm64 bash /stage2.sh
    - name: Desktop Environment and essentials
      run: sudo cp -v payload/stage3.sh fs-arm64/stage3.sh;sudo chroot fs-arm64 bash /stage3.sh
    - name: setupvnc
      run: sudo cp -v payload/stage4.sh fs-arm64/stage4.sh;sudo chroot fs-arm64 bash /stage4.sh
    - name: cleanup
      run: sudo chroot fs-arm64 apt clean
    - name: make tarbal
      run: sudo chroot fs-arm64 tar -cvpzf /focal-arm64.tar.gz --exclude-caches-all --exclude=/dev/*  --exclude=/sys/* --exclude=/proc/* --exclude=/run/* --exclude=/tmp/* --exclude=/focal-arm64.tar.gz /* --one-file-system || true
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: focal-arm64.tar.gz
        path : |
          fs-arm64/focal-arm64.tar.gz
    
