on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: setup deps
      run: sudo apt install axel binfmt-support qemu-user-static -y
    - name: clone fs
      run: axel https://cdimage.ubuntu.com/ubuntu-base/focal/daily/current/focal-base-armhf.tar.gz
    - name: extract fs
      run: mkdir -pv fs; sudo tar -xvpzf focal-base-armhf.tar.gz -C fs
    - name: Setup qemu
      run: sudo cp /bin/qemu-arm-static fs/bin ;sudo service binfmt-support start
    - name: mount fs
      run: sudo mount --rbind /dev fs/dev; sudo mount -t proc proc fs/proc;sudo mount -t sysfs /sys fs/sys
    - name: setup network
      run: sudo touch fs/etc/resolv.conf;echo nameserver 8.8.8.8 | sudo tee fs/etc/resolv.conf
    - name: fix up fs
      run: sudo cp -v payload/stage1.sh fs/stage1.sh; sudo cp -v payload/stage2.sh fs/stage2.sh; sudo chroot fs bash {/stage1.sh,/stage2.sh}
    - name: make tarbal
      run: sudo chroot tar -cvpzf /focal-armhf.tar.gz --exclude-caches-all --exclude=/dev/*  --exclude=/sys/* --exclude=/proc/* --exclude=/run/* --exclude=/tmp/* --exclude=/focal-armhf.tar.gz /* --one-file-system
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: focal-armhf.tar.gz
        path : |
          fs/focal-armhf.tar.gz
    
